application:
  security:
    jwt:
      # Key bí mật dùng để ký token (nên có độ dài tối thiểu 256-bit cho HS256)
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      # Thời gian hết hạn (ví dụ: 86400000 ms = 24 giờ)
      expiration: 86400000
spring:
  application:
    name: fin-track
  datasource:
    url: jdbc:mysql://localhost:3307/fin-track?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: fintrack_user
    password: fintrack_pass_2026
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
    mode: HTML

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    com.finance.tracker: DEBUG
    org.springframework.web: INFO
